<?php

/**
 * @file
 * Sth sth dark side.
 */

/**
 * Implements hook_requirements().
 */
function geolocation_gpx_requirements($phase) {
  $requirements = [];
  $requirements['geolocation_gpx_composer'] = [
    'title' => t('Geolocation GPX - Composer dependency'),
    'value' => t('Libraries installed'),
    'description' => t('Use "composer require sibyx/phpgpx:@RC" to install required library.'),
    'severity' => (class_exists('\\Drupal\\Core\\Extension\\Requirement\\RequirementSeverity') ? \Drupal\Core\Extension\Requirement\RequirementSeverity::OK : REQUIREMENT_OK),
  ];

  if (!class_exists('phpGPX\\phpGPX')) {
    $requirements['geolocation_gpx_composer']['value'] = t('Libraries not installed');
    $requirements['geolocation_gpx_composer']['severity'] = (class_exists('\\Drupal\\Core\\Extension\\Requirement\\RequirementSeverity') ? \Drupal\Core\Extension\Requirement\RequirementSeverity::Error : REQUIREMENT_ERROR);
  }

  return $requirements;
}
